### ISSUE TITLE
Pre-trained Models?

### ISSUE THREAD

**Issue by Yuliang-Zou** [linjian93/tf-flownet#1]
Hi, do you have pre-trained model weights for this code? Can you provide the download link to it?

Thank you!

**Comment by linjianz** [comment]
I've trained for a while, but the result is not so good. You may refer to https://lmb.informatik.uni-freiburg.de/resources/binaries/ for the author's trained model.

**Comment by saxenarohan97** [comment]
The authors have used Caffe for designing their models. Is it possible to use these pre-trained weights in TensorFlow?

**Comment by linjianz** [comment]
@saxenarohan97 Yes you can, refer to https://github.com/ethereon/caffe-tensorflow
